@echo off
cd backend
echo Starting Backend...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Running migrations...
python manage.py migrate
echo Starting server...
python manage.py runserver
